#!/bin/sh

# Build Linux ARM64

env GOOS=linux GOARCH=arm64 go build -tags=prod -o polyn ./cmd/polyn

cd install
env GOOS=linux GOARCH=arm64 go build -o ../setup ./cmd/setup

cd ../uninstall
env GOOS=linux GOARCH=arm64 go build -o ../uninstall-arm64

cd ..
mkdir PolyNode-linux-arm64
mv setup ./PolyNode-linux-arm64/setup

cd PolyNode-linux-arm64
mkdir PolyNode
cd ..
mv polyn ./PolyNode-linux-arm64/PolyNode/polyn

cp README.md ./PolyNode-linux-arm64/PolyNode
cp LICENSE ./PolyNode-linux-arm64/PolyNode
cp SECURITY.md ./PolyNode-linux-arm64/PolyNode

cd ./PolyNode-linux-arm64/PolyNode
mkdir uninstall
cd ../..
mv uninstall-arm64 ./PolyNode-linux-arm64/PolyNode/uninstall/uninstall

# Build Linux x64

env GOOS=linux GOARCH=amd64 go build -tags=prod -o polyn ./cmd/polyn

cd install
env GOOS=linux GOARCH=amd64 go build -o ../setup ./cmd/setup

cd ../uninstall
env GOOS=linux GOARCH=amd64 go build -o ../uninstall-x64

cd ..
mkdir PolyNode-linux-x64
mv setup ./PolyNode-linux-x64

cd PolyNode-linux-x64
mkdir PolyNode
cd ..
mv polyn ./PolyNode-linux-x64/PolyNode/polyn

cp README.md ./PolyNode-linux-x64/PolyNode
cp LICENSE ./PolyNode-linux-x64/PolyNode
cp SECURITY.md ./PolyNode-linux-x64/PolyNode

cd ./PolyNode-linux-x64/PolyNode
mkdir uninstall
cd ../..
mv uninstall-x64 ./PolyNode-linux-x64/PolyNode/uninstall/uninstall

# Build Linux Power LE 64-bit

env GOOS=linux GOARCH=ppc64le go build -tags=prod -o polyn ./cmd/polyn

cd install
env GOOS=linux GOARCH=ppc64le go build -o ../setup ./cmd/setup

cd ../uninstall
env GOOS=linux GOARCH=ppc64le go build -o ../uninstall-ppc64le

cd ..
mkdir PolyNode-linux-ppc64le
mv setup ./PolyNode-linux-ppc64le

cd PolyNode-linux-ppc64le
mkdir PolyNode
cd ..
mv polyn ./PolyNode-linux-ppc64le/PolyNode/polyn

cp README.md ./PolyNode-linux-ppc64le/PolyNode
cp LICENSE ./PolyNode-linux-ppc64le/PolyNode
cp SECURITY.md ./PolyNode-linux-ppc64le/PolyNode

cd ./PolyNode-linux-ppc64le/PolyNode
mkdir uninstall
cd ../..
mv uninstall-ppc64le ./PolyNode-linux-ppc64le/PolyNode/uninstall/uninstall

# Build Linux s390x

env GOOS=linux GOARCH=s390x go build -tags=prod -o polyn ./cmd/polyn

cd install
env GOOS=linux GOARCH=s390x go build -o ../setup ./cmd/setup

cd ../uninstall
env GOOS=linux GOARCH=s390x go build -o ../uninstall-s390x

cd ..
mkdir PolyNode-linux-s390x
mv setup ./PolyNode-linux-s390x

cd PolyNode-linux-s390x
mkdir PolyNode
cd ..
mv polyn ./PolyNode-linux-s390x/PolyNode/polyn

cp README.md ./PolyNode-linux-s390x/PolyNode
cp LICENSE ./PolyNode-linux-s390x/PolyNode
cp SECURITY.md ./PolyNode-linux-s390x/PolyNode

cd ./PolyNode-linux-s390x/PolyNode
mkdir uninstall
cd ../..
mv uninstall-s390x ./PolyNode-linux-s390x/PolyNode/uninstall/uninstall

# Bundle

tar -cJf PolyNode-linux-arm64.tar.xz PolyNode-linux-arm64
rm -rf PolyNode-linux-arm64

tar -cJf PolyNode-linux-x64.tar.xz PolyNode-linux-x64
rm -rf PolyNode-linux-x64

tar -cJf PolyNode-linux-ppc64le.tar.xz PolyNode-linux-ppc64le
rm -rf PolyNode-linux-ppc64le

tar -cJf PolyNode-linux-s390x.tar.xz PolyNode-linux-s390x
rm -rf PolyNode-linux-s390x
