#!/bin/sh

build() (
  goArch="$1"
  polynArch="$2"
  buildPolyn "$goArch"
  buildInstall "$goArch"
  buildUninstall "$goArch" "$polynArch"
  construct "$polynArch"
  bundle "$polynArch"
)

buildInstall() (
  cd install || exit
  env GOOS=linux GOARCH="$1" go build -ldflags="-s -w" -o ../setup ./cmd/setup
)

buildPolyn() {
  env GOOS=linux GOARCH="$1" go build -ldflags="-s -w" -tags=prod -o polyn ./cmd/polyn
}

buildUninstall() (
  cd uninstall || exit
  env GOOS=linux GOARCH="$1" go build -ldflags="-s -w" -o ../"uninstall-${2}"
)

bundle() {
  tar -czf "PolyNode-linux-${1}.tar.gz" "PolyNode-linux-${1}"
  tar -cJf "PolyNode-linux-${1}.tar.xz" "PolyNode-linux-${1}"
  rm -rf "PolyNode-linux-${1}"
}

construct() {
  mkdir -p "PolyNode-linux-${1}"/PolyNode/uninstall
  mv setup ./"PolyNode-linux-${1}"/setup
  mv polyn ./"PolyNode-linux-${1}"/PolyNode/polyn
  cp README.md LICENSE SECURITY.md ./"PolyNode-linux-${1}"/PolyNode
  mv "uninstall-${1}" ./"PolyNode-linux-${1}"/PolyNode/uninstall/uninstall
}

build arm64 arm64
build amd64 x64
build ppc64le ppc64le
build s390x s390x
