#!/bin/sh

buildPolyNode() {
  polynArch="$1"
  polynSuffix="${2:-$1}"
  baseDir="./PolyNode-linux-${polynSuffix}"
  polyNodeDir="${baseDir}/PolyNode"
  uninstallDir="${polyNodeDir}/uninstall"

  env GOOS=linux GOARCH="$polynArch" go build -ldflags="-s -w" -tags=prod -o polyn ./cmd/polyn

  (
    cd install || exit
    env GOOS=linux GOARCH="$polynArch" go build -ldflags="-s -w" -o ../setup ./cmd/setup
  )

  (
    cd uninstall || exit
    env GOOS=linux GOARCH="$polynArch" go build -ldflags="-s -w" -o "../uninstall-${polynSuffix}"
  )

  mkdir -p "$uninstallDir"

  mv setup "${baseDir}/setup"
  mv polyn "${polyNodeDir}/polyn"
  mv "uninstall-${polynSuffix}" "${uninstallDir}/uninstall"

  cp README.md LICENSE SECURITY.md "$polyNodeDir"

  tar -czf "${baseDir}.tar.gz" "$baseDir"
  tar -cJf "${baseDir}.tar.xz" "$baseDir"

  rm -rf "$baseDir"
}

buildPolyNode arm64
buildPolyNode amd64 x64
buildPolyNode ppc64le
buildPolyNode s390x
