#!/bin/sh

# Build AIX Power 64-bit

env GOOS=aix GOARCH=ppc64 go build -tags=prod -o polyn ./cmd/polyn

cd install
env GOOS=aix GOARCH=ppc64 go build -o ../setup ./cmd/setup

cd ../uninstall
env GOOS=aix GOARCH=ppc64 go build -o ../uninstall-ppc64

cd ..
mkdir PolyNode-aix-ppc64
mv setup ./PolyNode-aix-ppc64/setup

cd PolyNode-aix-ppc64
mkdir PolyNode
cd ..
cp polyn ./PolyNode-aix-ppc64/PolyNode

cp README.md ./PolyNode-aix-ppc64/PolyNode
cp LICENSE ./PolyNode-aix-ppc64/PolyNode
cp SECURITY.md ./PolyNode-aix-ppc64/PolyNode

cd ./PolyNode-aix-ppc64/PolyNode
mkdir uninstall
cd ../..
mv uninstall-ppc64 ./PolyNode-aix-ppc64/PolyNode/uninstall/uninstall

# Bundle

tar -czf PolyNode-aix-ppc64.tar.gz PolyNode-aix-ppc64
rm -rf PolyNode-aix-ppc64
