#!/bin/sh

sign=1

build() (
  goArch="$1"
  polynArch="$2"
  buildPolyn "$goArch"
  buildInstall "$goArch"
  buildUninstall "$goArch" "$polynArch"
  construct "$polynArch"
  bundle "$polynArch"
)

buildInstall() {
  (
    cd install || exit
    env GOOS=darwin GOARCH="$1" go build -ldflags="-s -w" -o ../setup ./cmd/setup
  )
  signBinary setup
}

buildPolyn() {
  env GOOS=darwin GOARCH="$1" go build -ldflags="-s -w" -tags=prod -o polyn ./cmd/polyn
  signBinary polyn
}

buildUninstall() {
  (
    cd uninstall || exit
    env GOOS=darwin GOARCH="$1" go build -ldflags="-s -w" -o ../"uninstall-${2}"
  )
  signBinary "uninstall-${2}"
}

bundle() {
  tar -czf "PolyNode-darwin-${1}.tar.gz" "PolyNode-darwin-${1}"
  rm -rf "PolyNode-darwin-${1}"
}

construct() {
  mkdir -p "PolyNode-darwin-${1}"/PolyNode/uninstall
  mv setup ./"PolyNode-darwin-${1}"/setup
  mv polyn ./"PolyNode-darwin-${1}"/PolyNode/polyn
  cp README.md LICENSE SECURITY.md ./"PolyNode-darwin-${1}"/PolyNode
  mv "uninstall-${1}" ./"PolyNode-darwin-${1}"/PolyNode/uninstall/uninstall
}

signBinary() {
  if [ "$sign" -eq 1 ]; then
    codesign -v -f --timestamp --options=runtime --sign="$CODESIGN_TEAM_ID" "$1"
    zip "${1}.zip" "$1"
    rm "$1"
    xcrun notarytool submit --apple-id="$CODESIGN_APPLE_ID" --team-id="$CODESIGN_TEAM_ID" --password="$CODESIGN_PASSWD" "${1}.zip"
    unzip "${1}.zip"
    rm "${1}.zip"
  fi
}

build arm64 arm64
build amd64 x64
